# Generated by Django 4.1 on 2022-08-31 15:08

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverapplication',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='driverschoolunit', chained_model_field='driverschoolunit', on_delete=django.db.models.deletion.CASCADE, to='school.courses', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='driverapplication',
            name='driverschoolunit',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='city', chained_model_field='city', on_delete=django.db.models.deletion.CASCADE, to='school.driverschoolunit', verbose_name='Філія автошколи'),
        ),
    ]
