# Generated by Django 4.1.1 on 2022-11-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeDriverApp',
        ),
    ]
