# Generated by Django 4.1 on 2022-08-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alphabet_area_category_city_courses_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverschool',
            name='image1',
            field=models.ImageField(default='schoolua/images/test-image1.jpg', upload_to='school/images/', verbose_name='Фото головне'),
        ),
        migrations.AlterField(
            model_name='driverschool',
            name='image2',
            field=models.ImageField(default='schoolua/images/test-image2.jpg', upload_to='school/images/', verbose_name='Фото 2'),
        ),
        migrations.AlterField(
            model_name='driverschool',
            name='image3',
            field=models.ImageField(default='schoolua/images/test-image3.jpg', upload_to='school/images/', verbose_name='Фото 3'),
        ),
        migrations.AlterField(
            model_name='driverschool',
            name='image4',
            field=models.ImageField(default='schoolua/images/test-image4.jpg', upload_to='school/images/', verbose_name='Фото 4'),
        ),
        migrations.AlterField(
            model_name='driverschool',
            name='image5',
            field=models.ImageField(default='schoolua/images/test-image5.jpg', upload_to='school/images/', verbose_name='Фото 5'),
        ),
    ]
