# Generated by Django 4.1 on 2022-09-06 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_driverapplication_driverschoolunit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverschoolunit',
            name='url',
            field=models.URLField(blank=True, max_length=1500, verbose_name='Геопозиція автошколи'),
        ),
    ]
