# Generated by Django 4.1 on 2022-09-16 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_alter_driverschoolunit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverschoolunit',
            name='driverschool_name',
            field=models.CharField(default='!', max_length=250, verbose_name='For application'),
        ),
    ]
